### ISSUE TITLE
Define project structure: single vs multiple repositories

### ISSUE THREAD

**Issue by jurra** [MurTree/dcctree#1]
Options:
- [ ] Everything in a monorepo (so python code and R in the same original MurTree)
- [ ] Separated repos for the wrappers
- [ ] Each wrapper holds a git submodule of cpp Murtree

Lets discuss pros and cons, we are leaning towards separate repos

**Comment by jurra** [comment]
In principle cpp codebase will be separate from wrappers. Then we decide how cpp code is chained with the python codebase. See pymurtree#2

**Comment by yiquintero** [comment]
The project will be organized as follows:
- All project repositories will be owned by a GitHub organization called MurTree
- The project will be split into three independent repositories:
    - murtree:  clone of the original BitBucket repository, contains only C++ code
    - pymurtree: python wrapper
    - murtree-data: datasets extracted from the original BitBucket repository (see  #4)

Note: if an R wrapper is developed in the future, it will be added as a separate repository under the MurTree organization
