### ISSUE TITLE
Clean up cpp main repo history which contains currently .obj files making the library very heavy

### ISSUE THREAD

**Issue by jurra** [MurTree/dcctree#2]
Currently the repo is about 50Mb when cloned, this is mainly due to the fact that *.obj binary files in the Release directory. Several ways to do it:

- Create an orphan branch completely empty and already copy the entire project except for the RElease folder
- Create an orphan branch and do cherry picking of the commits that didnt commited such files.

**Comment by yiquintero** [comment]
The .obj files (and any other unnecessary files, big or small) were deleted from the history of this repository using a `git rebase` operation. See issue #4
